package entities;
// Generated 25-mars-2023 15:30:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Creneaux generated by hbm2java
 */
public class Creneaux  implements java.io.Serializable {


     private Integer idCreneau;
     private Medecin medecin;
     private String hdebut;
     private String hfin;
     private Set<Rv> rvs = new HashSet<Rv>(0);

    public Creneaux() {
    }

    public Creneaux(Medecin medecin, String hdebut, String hfin) {
       this.medecin = medecin;
       this.hdebut = hdebut;
       this.hfin = hfin;
    }
    public Creneaux(Medecin medecin) {
        this.medecin = medecin;
    }
    public Creneaux(Medecin medecin, String hdebut, String hfin, Set<Rv> rvs) {
       this.medecin = medecin;
       this.hdebut = hdebut;
       this.hfin = hfin;
       this.rvs = rvs;
    }
   
    public Integer getIdCreneau() {
        return this.idCreneau;
    }
    
    public void setIdCreneau(Integer idCreneau) {
        this.idCreneau = idCreneau;
    }
    public Medecin getMedecin() {
        return this.medecin;
    }
    
    public void setMedecin(Medecin medecin) {
        this.medecin = medecin;
    }
    public String getHdebut() {
        return this.hdebut;
    }
    
    public void setHdebut(String hdebut) {
        this.hdebut = hdebut;
    }
    public String getHfin() {
        return this.hfin;
    }
    
    public void setHfin(String hfin) {
        this.hfin = hfin;
    }
    public Set<Rv> getRvs() {
        return this.rvs;
    }
    
    public void setRvs(Set<Rv> rvs) {
        this.rvs = rvs;
    }
    
    public String toString(){
        return "heure debut: "+this.hdebut+" heure fin: "+this.hfin+"_";
    }

}


