package entities;
// Generated 25-mars-2023 15:30:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medecin generated by hbm2java
 */
public class Medecin  implements java.io.Serializable {


     private Integer idMedecin;
     private String nom;
     private String prenom;
     private String titre;
     private Set<Creneaux> creneauxes = new HashSet<Creneaux>(0);

    public Medecin() {
    }
    
    public Medecin(String nom, String prenom, String titre) {
       this.nom = nom;
       this.prenom = prenom;
       this.titre = titre;
    }
    
    public Medecin(String nom, String prenom, String titre, Set<Creneaux> creneauxes) {
       this.nom = nom;
       this.prenom = prenom;
       this.titre = titre;
       this.creneauxes = creneauxes;
    }
   
    public Integer getIdMedecin() {
        return this.idMedecin;
    }
    
    public void setIdMedecin(Integer idMedecin) {
        this.idMedecin = idMedecin;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public Set<Creneaux> getCreneauxes() {
        return this.creneauxes;
    }
    
    public void setCreneauxes(Set<Creneaux> creneauxes) {
        this.creneauxes = creneauxes;
    }

    public String toString(){
        return " "+nom+"_"+prenom+"_"+titre;
    }

}


