package entities;
// Generated 25-mars-2023 15:30:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rv generated by hbm2java
 */
public class Rv  implements java.io.Serializable {


     private Integer idRv;
     private Client client;
     private Creneaux creneaux;
     private Date jour;

    public Rv() {
    }

    public Rv(Client client, Creneaux creneaux, Date jour) {
       this.client = client;
       this.creneaux = creneaux;
       this.jour = jour;
    }
   
    public Integer getIdRv() {
        return this.idRv;
    }
    
    public void setIdRv(Integer idRv) {
        this.idRv = idRv;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Creneaux getCreneaux() {
        return this.creneaux;
    }
    
    public void setCreneaux(Creneaux creneaux) {
        this.creneaux = creneaux;
    }
    public Date getJour() {
        return this.jour;
    }
    
    public void setJour(Date jour) {
        this.jour = jour;
    }




}


